export type Language = 'english' | 'hinglish';
export interface Explanation { id: string; title: string; meaning: string; suggestions: string[]; confidence: 'pattern-match'; matchedPattern: string }
interface Rule { id: string; title: string; pattern: RegExp; english: string; hinglish: string; suggestions: string[] }
const rules: Rule[] = [
 { id:'node-port-in-use', title:'That port already has a tenant', pattern:/\bEADDRINUSE\b/i, english:'A process is already listening on the requested address/port. This does not identify which process or prove it is safe to stop.', hinglish:'Port pe pehle se koi baitha hai. Kaun hai aur band karna safe hai ya nahi, pehle check karo.', suggestions:['Inspect listening processes using your OS tools, or choose another port.','Stop a process only after confirming it belongs to your project.'] },
 { id:'node-module-missing', title:'The module did not make it to the party', pattern:/(?:Cannot find module\s+['"]|Cannot find package\s+['"]|\bERR_MODULE_NOT_FOUND\b)/i, english:'Node could not resolve a module or package. It may be uninstalled, a misspelled path, or an export/extension mismatch.', hinglish:'Node ko module mila nahi. Missing install bhi ho sakta hai, ya path/extension/export ka chakkar.', suggestions:['Check the import spelling, case, extension and package exports.','Compare package.json and the lockfile before changing dependencies.'] },
 { id:'npm-dependency-conflict', title:'Your dependencies are not getting along', pattern:/\bERESOLVE\b|unable to resolve dependency tree/i, english:'npm could not satisfy the dependency constraints, often because peer dependency versions disagree.', hinglish:'Dependencies ki versions mein jhagda hai. Force karke chup karana fix nahi hota.', suggestions:['Read the conflicting peer versions in the original log.','Choose compatible versions; do not start with --force or --legacy-peer-deps.'] },
 { id:'npm-engine-mismatch', title:'Right package, wrong engine', pattern:/\bEBADENGINE\b|Unsupported engine/i, english:'A package declares runtime versions that differ from your current environment. A warning may not be the fatal error.', hinglish:'Package ko alag runtime version chahiye. Warning hai ya asli failure, poora log dekho.', suggestions:['Compare the reported required and current Node/npm versions.','Use the project-declared supported runtime, rather than assuming latest is compatible.'] },
 { id:'file-permission', title:'The file said no', pattern:/\bEACCES\b|\bEPERM\b/i, english:'The operation was denied by a permission or OS policy. The cause could also be a locked file or managed environment.', hinglish:'OS ne permission nahi di. Har baar sudo lagana solution nahi hai.', suggestions:['Check the path owner, permissions and whether another process holds the file.','Do not blindly use sudo or recursively loosen permissions.'] },
 { id:'file-missing', title:'That path is not where you think it is', pattern:/\bENOENT\b/i, english:'A requested file, directory or executable was not found. Relative paths depend on the current working directory.', hinglish:'Path ya executable mila nahi. Tum jis folder mein ho, usse relative path check karo.', suggestions:['Verify the working directory and the exact path, including filename case.','Confirm any expected build artifact was actually produced.'] },
 { id:'network-refused', title:'Nobody answered the door', pattern:/\bECONNREFUSED\b/i, english:'The target refused the network connection. The service might be stopped or listening on another address/port.', hinglish:'Connection ka darwaza nahi khula. Service chal rahi hai aur sahi port pe hai?', suggestions:['Check whether the intended local service is running and listening on the expected port.','Verify host, port and proxy settings; do not assume a retry fixes configuration.'] },
 { id:'dns-failure', title:'The address book is confused', pattern:/\bENOTFOUND\b|\bEAI_AGAIN\b/i, english:'The hostname could not be resolved, or DNS lookup temporarily failed.', hinglish:'Hostname ka address nahi mila. Spelling, DNS aur network check karo.', suggestions:['Check hostname spelling and your network/DNS configuration.','For EAI_AGAIN, a later retry may help, but persistent failure needs investigation.'] },
 { id:'git-not-repository', title:'Git does not know this neighborhood', pattern:/fatal:\s*not a git repository/i, english:'The current directory is not inside a Git repository, or Git cannot locate its metadata.', hinglish:'Git ko yahan repo nahi mila. Sahi project folder mein aaye ho?', suggestions:['Confirm the working directory and whether this is a clone with .git metadata.','Do not run git init just to silence the error if you meant to use an existing repository.'] },
 { id:'git-unrelated-histories', title:'These branches have never met', pattern:/fatal:\s*refusing to merge unrelated histories/i, english:'The histories have no shared ancestor. Combining them may be intentional, but should not be treated as a routine update.', hinglish:'Dono histories ka common ancestor nahi hai. Shaadi karwani hai ya galat remote hai, pehle decide karo.', suggestions:['Verify repository and remote identity before merging.','Review both histories; use an unrelated-history override only if combining them is intended.'] },
 { id:'shell-command-missing', title:'Your shell has never heard of it', pattern:/(?:command not found:\s*\S+|:\s*\S+: command not found|is not recognized as an internal or external command)/i, english:'The shell cannot locate that command. It might not be installed, or its directory is not on PATH.', hinglish:'Shell ko command pata nahi. Install aur PATH dono check karo.', suggestions:['Check the executable spelling and whether it is installed for this environment.','Inspect PATH or the project-provided script before installing a similarly named package.'] },
 { id:'json-invalid', title:'JSON objects to that punctuation', pattern:/SyntaxError:.*(?:JSON|Unexpected token|Expected property name|Unterminated string)|Unexpected end of JSON input/i, english:'Parsing failed. If the input was supposed to be JSON, check its syntax and whether the source returned HTML or truncated content instead.', hinglish:'Parser atak gaya. JSON expected tha toh syntax dekho; ho sakta hai response HTML ya adhoora ho.', suggestions:['Inspect the original input near the reported position.','Check for trailing commas, unquoted keys, truncation and an unexpected content type.'] }
];
/** Input stays local. Pattern matches are diagnoses to investigate, not certain root causes. */
export function explain(input: string, language: Language = 'english'): Explanation[] {
 if (typeof input !== 'string') throw new TypeError('input must be a string');
 if (!['english','hinglish'].includes(language)) throw new TypeError('language must be english or hinglish');
 if (Buffer.byteLength(input,'utf8') > 1_048_576) throw new RangeError('Input exceeds 1 MiB');
 // Normalize terminal control sequences for matching; never echo input into output.
 const text = input.replace(/\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)/g,'').replace(/\x1b\[[0-?]*[ -/]*[@-~]/g,'');
 return rules.filter(rule=>rule.pattern.test(text)).map(rule=>({id:rule.id,title:rule.title,meaning:language==='hinglish'?rule.hinglish:rule.english,suggestions:[...rule.suggestions],confidence:'pattern-match',matchedPattern:rule.id}));
}
